export const MENU_ITEMS = [
  {
    id: 'green-apple-boba',
    name: 'Green Apple Boba',
    category: 'boba',
    price: 150,
    badge: 'Crisp & Tangy',
    emoji: '🍏',
    color: 'from-emerald-400 to-green-600',
    border: 'border-green-300',
    lightBg: 'bg-green-50',
    textAccent: 'text-emerald-700',
    tagBg: 'bg-emerald-100 text-emerald-800',
    description: 'Refreshing green apple iced tea with chewy tapioca pearls',
  },
  {
    id: 'orange-boba',
    name: 'Orange Boba',
    category: 'boba',
    price: 150,
    badge: 'Zesty Citrus',
    emoji: '🍊',
    color: 'from-amber-400 to-orange-500',
    border: 'border-orange-300',
    lightBg: 'bg-orange-50',
    textAccent: 'text-orange-700',
    tagBg: 'bg-orange-100 text-orange-800',
    description: 'Sweet and tangy orange infusion with popping boba pearls',
  },
  {
    id: 'strawberry-boba',
    name: 'Strawberry Boba',
    category: 'boba',
    price: 150,
    badge: 'Bestseller',
    emoji: '🍓',
    color: 'from-rose-400 to-pink-600',
    border: 'border-pink-300',
    lightBg: 'bg-pink-50',
    textAccent: 'text-rose-700',
    tagBg: 'bg-rose-100 text-rose-800',
    description: 'Creamy sweet strawberry milk tea with rich boba pearls',
  },
  {
    id: 'blueberry-boba',
    name: 'Blueberry Boba',
    category: 'boba',
    price: 150,
    badge: 'Wild Berry',
    emoji: '🫐',
    color: 'from-indigo-400 to-violet-600',
    border: 'border-indigo-300',
    lightBg: 'bg-indigo-50',
    textAccent: 'text-indigo-700',
    tagBg: 'bg-indigo-100 text-indigo-800',
    description: 'Luscious wild blueberry iced tea with burst of pearls',
  },
  {
    id: 'steamed-momos',
    name: 'Steamed Momos',
    category: 'momos',
    price: 120,
    badge: 'Hot & Steaming',
    emoji: '🥟',
    color: 'from-amber-500 to-red-600',
    border: 'border-amber-300',
    lightBg: 'bg-amber-50',
    textAccent: 'text-amber-800',
    tagBg: 'bg-amber-100 text-amber-900',
    description: 'Freshly steamed juicy vegetable & spiced momos with spicy red dip',
  },
  {
    id: 'boba-momo-combo',
    name: 'Boba + Momo Combo',
    category: 'combo',
    price: 250,
    badge: 'Special Combo',
    emoji: '🍱',
    color: 'from-purple-500 to-rose-500',
    border: 'border-purple-300',
    lightBg: 'bg-purple-50',
    textAccent: 'text-purple-700',
    tagBg: 'bg-purple-100 text-purple-800',
    description: '1 Boba drink of choice + 1 plate steamed momos at a special combo price',
  },
];

export const PAYMENT_METHODS = {
  CASH: 'Cash',
  ONLINE: 'Online',
};

export const ORDER_STATUS = {
  PREPARING: 'preparing',
  READY: 'ready',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
};
